### ISSUE TITLE
use kwargs for bind params

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/postgres.py#32]
Suggested by @dstufft in [IRC](https://botbot.me/freenode/gittip/msg/7660935/).

We currently pass kwargs through to the cursor constructor. How would we handle that instead? Make some kwargs magic (eep!)?

**Comment by whit537** [comment]
I really want this.

**Comment by Changaco** [comment]
I would rather pass nothing at all, pulling values directly from locals and globals instead. Unfortunately [PEP 498](https://www.python.org/dev/peps/pep-0498/) didn't take into account the need for escaping so we can't use them for SQL strings.

**Comment by Changaco** [comment]
Done in #79.
