### ISSUE TITLE
change from CC0 to MIT

### ISSUE THREAD

**Issue by chadwhitacre** [chadwhitacre/postgres.py#36]
CC0 is problematic outside the U.S. SQLite solves the problem by charging people who care $1,000. We should just drop back to MIT for path of least resistance.

**Comment by techtonik** [comment]
What is the problem with CC0? There is a problem with public domain and with software licensing in whole, but nothing specific with CC0 that I know of. I even think that CC0 is more acceptable outside U.S. than software licenses.

**Comment by natiiix** [comment]
This should have probably been closed after d44d9b16499540e1e025cccf51a2a47fd3b71a18.

**Comment by chadwhitacre** [comment]
I suppose so, yes. :)
