### ISSUE TITLE
Don't check for column name restrictions when receiving a single expression

### ISSUE THREAD

**Issue by rohitpaulk** [chadwhitacre/postgres.py#47]
Reference: https://github.com/gratipay/gratipay.com/pull/3282

Doesn't work:
`db.one("SELECT 1 FROM participants LIMIT 1")`

Works:
`db.one("SELECT 1 AS something FROM participants LIMIT 1")`. 

Postgres returns `?column?` as the column name if it can't find one, here's the error thrown on our side:

```
ValueError: Type names and field names can only contain alphanumeric characters and underscores: '?column?'
```

**Comment by Changaco** [comment]
More recent versions of `psycopg2` no longer choke on unconventional field names.
